services:
  - type: web
    name: next-js
    runtime: node
    plan: free
    buildCommand: pnpm install; pnpm build
    startCommand: pnpm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        value: khafo5852@gmail.com
      - key: EMAIL_PASSWORD
        value: ddltdbezymgzibqx
    domains:
      - name: boemin.com
        type: primary
        autoAssign: true
        autoAssignSubdomain: true